
name: Telegram Label Extraction

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-labeling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run labeling script
      run: |
        python your_label_script.py
